changelog:
  exclude:
    labels:
      - ignore-for-release
      - github-actions
      - skip-changelog
    authors:
      - bot-account
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
        - feat
    - title: Bug fixes 🐛
      labels:
        - bug
        - fix
    - title: Other Changes 🔄
      labels:
        - '*'
